### PR TITLE
Update bookmarks.js

### PR DESCRIPTION
**Pull request by 2knal**
Adding a new bookmark, for dev purposes.

### CODE REVIEW

**Comment by mraza007** [comment]
Please add the tags

**Comment by 2knal** [comment]
In the bookmarks.md right?

**Comment by mraza007** [comment]
In bookmarks.js file

**Comment by 2knal** [comment]
Is it fine now?

**Comment by mraza007** [comment]
Just to clarify what files did you changed

**Comment by 2knal** [comment]
Updated bookmarks.js and bookmarks.md with the relevant tags.

**Pull request merged**
