### PR TITLE
save bookmarks to local storage

### PR DESCRIPTION
**Pull request by sliee17**
#16

### CODE REVIEW

**Comment by sliee17** [comment]
@mraza007 it seems the best way of implementing of saving bookmarks is to have an API. The only way to do it in client side is to let the user download an updated file of the bookmark.json which I think is inconvenient for the user

**Comment by mraza007** [comment]
Look great to me

**Comment by mraza007** [comment]
I haven't tested it yet but how does it actually works

**Comment by mraza007** [comment]
Didn't add the delete button

**Pull request merged**
